# 2.5.1 Rules of the Game
The game uses an infinite-sized rectangular grid of cells in which each cell is either
empty or occupied by an organism. The occupied cells are said to be alive, whereas
the empty ones are dead. The game is played over a specific period of time with each
turn creating a new “generation” based on the arrangement of live organisms in
the current configuration. The status of a cell in the next generation is determined
by applying the following four basic rules to each cell in the current configuration:
1. If a cell is alive and has either two or three live neighbors, the cell remains
alive in the next generation. The neighbors are the eight cells immediately
surrounding a cell: vertically, horizontally, and diagonally.
![description](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTEyCe27XvtN0AvN4Gt1QZXGIPug8tNXD9E4L0hOjwrx76Wh72)
2. A living cell that has no live neighbors or a single live neighbor dies from
isolation in the next generation.
3. A living cell that has four or more live neighbors dies from overpopulation in
the next generation.
4. A dead cell with exactly three live neighbors results in a birth and becomes
alive in the next generation. All other dead cells remain dead in the next
generation.

## Some description(Rules)
![a](https://www.researchgate.net/publication/339605473/figure/fig5/AS:869062565437443@1584212070801/Rules-of-Conways-Game-of-Life.png)
## Active
![b](https://jimblackler.net/blog/wp-content/uploads/2014/10/bigpic.png)


In [19]:
#the game of line
import numpy as np
import time

def numRows():
    nrows = int(input("Nhập vào số hàng: "))
    return nrows

def numCols():
    ncols = int(input("Nhập vào số cột: "))
    return ncols

# hàm tạo grid
def LifeGrid():
    # that function show a grid include nrows and ncols
    nrows = numRows()
    ncols = numCols()

    grid = np.zeros((nrows, ncols), dtype=int)
    # print(grid)
    # gắn cho 1 ô is alive
    grid[2][2] = 1
    print(grid)
    
    # 1 is alive, 0 is dead

def configre(coordList):
    # create tọa độ alive
    coordList = list(map(int, input("Just enter two value: ").split()))
    
     
def clearCell(a, row, col):
    # xóa ô riêng lẻ và set it thành trạng thái dead
    b = np.zeros((10, 10), dtype=int )   
    for i in range(1, row-1):
        for j in range(1, col-1):
            if a[i, j] == 1:
                if numLiveNeighbors(a, i, j) == 0 or numLiveNeighbors(a, i, j) == 1 or numLiveNeighbors(a, i, j) >= 4:
                    b[i, j] = 0
                if numLiveNeighbors(a, i, j) == 2 or numLiveNeighbors(a, i, j) == 3:
                    b[i, j] =1
    return b


def setCell(a, row, col):
    b = np.zeros((10, 10), dtype=int )   
    for i in range(1, row-1):
        for j in range(1, col-1):
            if a[i, j] == 0:
                    if numLiveNeighbors(a, i, j) == 3:
                        b[i, j] = 1
            else:
                if numLiveNeighbors(a, i, j) == 2 or numLiveNeighbors(a, i, j) == 3:
                    b[i, j] = 1   
    return b
    
    
def isLiveCell(a, row, col):
    # trả về giá trị boolean cho biết ô đã cho (row, col) có chứa 1 sinh vật sống hay không
    # chú ý: chỉ số ô phải nằm trong phạm vi hợp lệ
    return a[row, col] == 1

def numLiveNeighbors(a, row, col):
    # trả về số lượng hàng xóm của ô đã cho (row, col)
    # các hàng xóm nằm bên ngoài lưới coi như chết
    # chú ý: chỉ số hàng và cột của ô phải nằm trong phạm vi cho phép
    count = 0
    if a[row-1, col-1] == 1:
        count+=1
    if a[row-1, col] == 1:
        count+=1
    if a[row-1, col+1] == 1:
        count+=1
    if a[row, col-1] == 1:
        count+=1
    if a[row, col+1] == 1:
        count+=1
    if a[row+1, col-1] == 1:
        count+=1
    if a[row+1, col] == 1:
        count+=1
    if a[row+1, col+1] == 1:
        count+=1
    return count

def sort(sum):
    for i in range(len(sum)):
    	for j in range(len(sum)):
    		if sum[i, j]>1:
    			sum[i, j] =1



##----------------------------------o0o--------------------------------------##
nrows = numRows()
ncols = numCols()

cell1 = np.zeros((nrows, ncols), dtype=int )   


# thay vì gắn ô sống như thế này thì mình dùng configue để nhập thay vì phải duyệt cả list


# khởi tạo giá trị alive của cell tại đây
cell1[5,5] = 1
cell1[4,5] = 1
cell1[4,4] = 1
cell1[4,3] = 1
cell1[5,3] = 1
cell1[6,3] = 1
cell1[6,5] = 1
cell1[6,4] = 1


cell2 = cell1

# LifeGrid()
print("Ban đầu:")
print(cell1) 

i = 1
while True:
	print("lần ", i, ": ")
	cell2 = setCell(cell2, 10, 10)
	cell1 = clearCell(cell1, 10, 10) 
	sum = cell1+cell2
	sort(sum)
	print(sum)
	cell2 = sum
	cell1 = sum
	time.sleep(2)
	i+=1
    # biến dừng vòng lặp vì có thể vô hạn
	if i == 5:
		break
##_---------------------------------o0o-------------------------------------#    

Nhập vào số hàng: 10
Nhập vào số cột: 10
Ban đầu:
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
lần  1 : 
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0]
 [0 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
lần  2 : 
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 1 1 0 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
lần  3 : 
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 1 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 