In [2]:
#the game of line
import numpy as np
import time

def configre(coordList):
    # create tọa độ alive
    coordList = list(map(int, input("Just enter two value: ").split()))
    
def clearCell(a, row, col):# hàm chết đi. chuyển ô sống thành chết
    b = np.zeros((row, col), dtype=int)   
    for i in range(1, row-1):
        for j in range(1, col-1):
            if a[i, j] == 1:
                if numLiveNeighbors(a, i, j) == 0 or numLiveNeighbors(a, i, j) == 1 or numLiveNeighbors(a, i, j) >= 4:
                    b[i, j] = 0
    return b


def setCell(a, row, col):# hàm hồi sinh
    b = np.zeros((row, col), dtype=int)   
    for i in range(1, row-1):
        for j in range(1, col-1):
            if a[i, j] == 0:
                    if numLiveNeighbors(a, i, j) == 3:
                        b[i, j] = 1
            else:
                if numLiveNeighbors(a, i, j) == 2 or numLiveNeighbors(a, i, j) == 3:
                    b[i, j] = 1   
    return b   

def numLiveNeighbors(a, row, col):# tối ưu nhờ thư viện numpy
    rows, cols = a.shape
    rmin, rmax, cmin, cmax = max(0, row-1), min(rows-1, row+1), max(0, col-1), min(cols-1, col+1)
    submatrix = a[rmin:rmax+1, cmin:cmax+1]
    count = np.sum(submatrix) - a[row, col]
    return count

nrows = int(input("Nhập vào số hàng(>2): "))
ncols = int(input("Nhập vào số cột(>2): "))

cell1 = np.zeros((nrows, ncols), dtype=int)   

# thay vì gắn ô sống như thế này thì mình dùng configue

cell1[5,5] = 1
cell1[4,5] = 1
cell1[4,4] = 1
cell1[4,3] = 1
cell1[5,3] = 1
cell1[6,3] = 1
cell1[6,5] = 1
cell1[6,4] = 1

cell2 = cell1

print("Ban đầu:")
print(cell1) 

i = 1
while True:
	print("lần ", i, ": ")
	cell2 = setCell(cell2, nrows, ncols)
	cell1 = clearCell(cell1, nrows, ncols) 
	sum = cell1+cell2
	print(sum)
	cell2 = sum
	cell1 = sum
	time.sleep(2)
	i+=1
    # biến dừng vòng lặp vì có thể vô hạn
	if i == 5:
		break
    

Nhập vào số hàng(>2): 15
Nhập vào số cột(>2): 15
Ban đầu:
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
lần  1 : 
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0